// <auto-generated />
namespace MVC_WEB_Page.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Friends : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Friends));
        
        string IMigrationMetadata.Id
        {
            get { return "201412301418285_Friends"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
