// <auto-generated />
namespace MVC_WEB_Page.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Messages1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messages1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412311109593_Messages1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
